### ISSUE TITLE
Dynamics TODO list

### ISSUE THREAD

**Issue by dallan-keylogic** [IDAES/idaes-pse#1490]
There are many outstanding issues with dynamic or multiperiod models that need to be resolved. They will be aggregated in this issue. This list is incomplete; you can help by expanding it.

- [ ] Standardize behavior of initialization routines when more than one time point is present
- [ ] Revisit `process_base.fix_initial_conditions` and roll out standardized methods to provide initial conditions for dynamic models by loading in a `.json` file as well as solving a steady-state problem at `t0`.
- [ ] Reevaluate whether every model that allows `dynamic=True` should allow it, or whether it should be retired (`Heater`, I'm looking at you).

**Comment by andrewlee94** [comment]
A few more thoughts for inclusion (I suggest those with more experience think about these and add any important ones above):

1. Support normalized time domains - this could just be a new config argument to flowsheet block, which adds a scaling factor that can be picked up by control volumes.
2. Look at standardizing multiperiod models, as different projects seem to have implemented their own approaches. Notably, `FlowsheetBlock` already supports multiperiod models by setting `dynamic=False` and providing a `time_set` argument (effectively creating steady state models at each time element).

**Comment by Robbybp** [comment]
> Revisit process_base.fix_initial_conditions and roll out standardized methods to provide initial conditions for dynamic models by loading in a .json file as well as solving a steady-state problem at t0.

I have written some tools that may be useful for this, e.g. [this example](https://github.com/Pyomo/pyomo/blob/main/pyomo/contrib/mpc/examples/cstr/run_mpc.py). See lines 54-55, where I load data from a steady state model into plant and controller models for initialization. The data could also come from a dynamic model or a json file.
