### ISSUE TITLE
macOS Binaries

### ISSUE THREAD

**Issue by eslickj** [IDAES/idaes-pse#157]
We need to macOS binaries for completeness in our install instruction coverage.  We have ARM64 binaries now is that sufficient?  If we need x86_64, how are we going to get there?  Maybe GitHub actions without HSL could be a step toward that.

----
Related issues and PRs:
- [x] Binaries for ARM64
- [ ] CI testing for ARM64 binaries (currently done manually with VM)
- [x] IDAES/idaes-ext#69 - Add support for macOS x64_86 (everything but HSL solvers)
- [x] IDAES/idaes-pse#162 - Allow ideas get-extensions to run with macOS
- [x] IDAES/idaes-pse#163 -  Updatedate get-extensions command, prep for OSX
- [x] IDAES/idaes-ext#70 - Add support and instructions for compiling on macOS, https://github.com/IDAES/idaes-ext/pull/173
- [x] #148 Tests fail after vanilla "developer" IDAES install on macOS
- [x] Builds for ARM64 https://github.com/IDAES/idaes-ext/pull/201, https://github.com/IDAES/idaes-ext/pull/172

**Comment by adowling2** [comment]
See progress in https://github.com/IDAES/idaes-ext/issues/69
