### ISSUE TITLE
MEA model TODO list

### ISSUE THREAD

**Issue by jghouse88** [IDAES/idaes-pse#244]
Tracking TODOs from PR #140 and feature branch solvent_column:

- [ ] Tests need to be standardized.
    - [ ] Test marks are inconsistent
    - [ ] Need unit consistency checks
    - [ ] Check how pressure drop is handled. At one point, the initialization routine was changing the model state regarding pressure
    - [ ] Need to use initialization tester (this may depend on handling pressure above)
    - [ ] Need more verification checks (material and energy conservation, more asserts for model results)
    - [ ] Need more modular testing of build, initialization and solve steps
- [x] Rename `phe` model to `PlateHeatExchanger`
- [ ] Check for unit consistency and consider standardizing units. Property units are currently mixed (e.g. some using cm**3)
- [ ] Standardize naming of some variables - two I noted were `lnk_eq_conc` (consider if there is or should be a standard name) and `enth_liq_dens` (should be `enth_vol_liq`).
- [ ] Reaction package as a config argument and integrate with model
- [x] Remove reference to the time domain, and just make a local alias instead
- [x] More descriptive name for the var ` self.N_v`
- [ ] Create indexed vars for `yi`
- [x] Switch to using IDAES logger instead of Python `warnings` module
- [x] Change logger messages from all caps to normal
- [ ] Check vars fixed in the model (either convert to params or remove fixing in code) @andrewlee94 - I think I prefer `Vars` for most of these.
- [ ] Column pressure and options. The model currently provides config argument for options which do not exist. Also, column pressure is fixed via a config argument with a somewhat arbitrary default value.
- [ ] Review initialization routine. Logging should be standardized, and we should check if homotopy is required when using MA27 as the linear solver.
- [ ] Plate Heat Exchanger model directly references parameters from property package

Less Important:
- [ ] Consider whether plotting functions should live in a separate utility module
- [ ] Model report functions

**Comment by andrewlee94** [comment]
This issue should be rendered moot by #766 which replaces the previous MEA model with a new generic column model.
